<a href="https://colab.research.google.com/github/cdevine2021/Data_Sci/blob/main/Devine_Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Stats Notebook #3

# Loops

In [ ]:
for i in range(10):
  print(i)
  # printing 10 numbers starting from 0

0
1
2
3
4
5
6
7
8
9


In [ ]:
for i in range(5,8):
  print(i)
  #printing only the numbers between 5 and 8

5
6
7


In [ ]:
for i in range(3):
  print("Test Number: ",i)
  #printing 3 numbers starting with 0 but each number has test number in front of it.

Test Number:  0
Test Number:  1
Test Number:  2


#Functions

In [ ]:
def square(x):
  return x**2
# defing the square of a number function

In [ ]:
square(5)
# squaring 5

25

In [ ]:
square(123456)
# using the sqaure function to square 123456.

15241383936

In [ ]:
square(square(5))
# squaring 5 twice.

625

In [ ]:
square(square(square(5)))
# using the square function to square 5 three times.

390625

In [ ]:
def add_two(x):
  return x+2
  # defining another function of adding two to a number.

In [ ]:
add_two(5)
# adding 2 to 5

7

In [ ]:
square(add_two(5))
# adding two to 5 and then squaring that number

49

In [ ]:
choice = "apples"
# defining choice as apples.

In [ ]:
if choice == "apple":

    print("You choose apples.")

else:

    print("You did not choose apples.")
  # if its choice then you choose apples. if not then the it shows you did not choose apples.

You choose apples.


In [ ]:
choice = "orange"
# changing the choice to oranges.

In [ ]:
if choice == "apple":

    print("You choose apples.")

elif choice == "oranges":

    print("You choose oranges.")

else:

    print("You did not choose apples or oranges.")
      # if its choice then you choose apples. if not then the it shows you choose oranges. and if its neither it shows you did not choose apples or oranges.

You did not choose apples or oranges.


#User Input

In [ ]:
#choice = input("Please enter your choice (i.e. apple): ")

In [ ]:
choice
# choice equals oranges

'orange'

In [ ]:
if choice == "apple":

    print("You choose apples.")

elif choice == "oranges":

    print("You choose oranges.")

else:
    
    print("You did not choose apples or oranges.")
   #if its choice then you choose apples. if not then the it shows you choose oranges. and if its neither it shows you did not choose apples or oranges.

You did not choose apples or oranges.


In [ ]:
import numpy as np
#importing numpy as np

In [ ]:
np.random.permutation(52)
#importing a random order of 52 numbers

array([43, 10,  4,  0, 33, 35, 48, 25, 44, 51, 15, 22,  1, 14, 26, 13, 30,
       38, 27, 12, 21, 11, 37,  3, 42, 19, 29,  2, 36, 16, 39, 40,  8, 24,
       20,  9, 41,  7, 45, 17, 34, 50, 28, 49,  5, 23, 46, 31, 47,  6, 32,
       18])

In [ ]:
cards = np.random.permutation(52)
# usig cards as the meaning for np.random.permutation(52)

In [ ]:
cards
# showing what cards means

array([32, 22,  8, 38, 20,  3, 24, 18, 33, 34, 39, 41, 29,  1, 30, 47, 16,
       23,  9,  4, 19,  2, 15, 21,  7, 40, 44, 48, 31, 17, 25, 49, 45, 36,
       50, 27, 37, 42, 46,  5, 10, 13,  0, 26, 12, 14, 35, 51, 28, 11, 43,
        6])

In [ ]:
cards[0]
# showing the card defined as 0

32

In [ ]:
cards[1]
# the number 1 card. or the first card

22

In [ ]:
cards[2]
# the second card

8

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [ ]:
np.arange(52).reshape(4,13)
# arranging the 52 cards into 4 suits and 13 numbers

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [ ]:
np.arange(52).reshape(4,13)%13
 #arranging the 52 cards into 4 suits and 13 numbers but only up to 13

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [ ]:
np.arange(52).reshape(4,13)//13
# arranging the 52 cards but only using 3 numbers.

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [ ]:
suits = ['Clubs','Spades','Hearts','Diamonds']
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King']
# defining suits and names

In [ ]:
suits
# showing what suits is

['Clubs', 'Spades', 'Hearts', 'Diamonds']

In [ ]:
suits[0]
# showing the first suits

'Clubs'

In [ ]:
names
# showing what the names are

['Ace',
 'Two',
 'Three',
 'Four',
 'Five',
 'Six',
 'Seven',
 'Eight',
 'Nine',
 'Ten',
 'Jack',
 'Queen',
 'King']

In [ ]:
names[1]
# showing the second name

'Two'

In [ ]:
def card_name(card_number):

    suit = card_number//13
    name = card_number%13

    return names[name] + " of " + suits[suit]
# defining the card name and card number 

In [ ]:
card_name(0)
# card name of the first one is Ace of Clubs

'Ace of Clubs'

In [ ]:
card_name(51)
# the 51st card name

'King of Diamonds'

In [ ]:
cards = np.random.permutation(52)
# random order of the 52 cards

In [ ]:
top_of_deck           = card_name(cards[0])
second_card_in_deck   = card_name(cards[1])
last_card_in_deck     = card_name(cards[-1])
# defining the top of deck, the second card in deck, and last card in deck

In [ ]:
top_of_deck,second_card_in_deck,last_card_in_deck
# showing what the first card name is, the 2 card name is, and 2nd to last card.

('Two of Clubs', 'Four of Clubs', 'Queen of Diamonds')

In [ ]:
for i in range(5):
    print(card_name(cards[i]))
# printing 5 card names from the card deck.

Two of Clubs
Four of Clubs
King of Hearts
Eight of Diamonds
Queen of Clubs


In [ ]:
for i in range(15):
    print(card_name(cards[i]))
# printing 15 cards from the deck of cards

Two of Clubs
Four of Clubs
King of Hearts
Eight of Diamonds
Queen of Clubs
King of Clubs
Jack of Diamonds
Four of Hearts
Queen of Hearts
King of Spades
Jack of Spades
Eight of Spades
Six of Clubs
Three of Clubs
Seven of Hearts


In [ ]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/"
card_url_tail = ".png"


In [ ]:
suit = ['k','p','s','l']
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']
# defining the name card and suit with the set of each card.

In [ ]:
i = np.random.randint(4)
j = np.random.randint(13)

In [ ]:
i,j

(2, 6)

In [ ]:
suit[i]

's'

In [ ]:
card[j]

'7'

In [ ]:
from IPython.core.display import display, HTML

In [ ]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))
  # the defining of the displaying of the image 

In [ ]:
img = card_url_head + suit[i] + card[j] + card_url_tail
# the image is the url of the url's of card head and card tail

In [ ]:
show_img(img)
# showing the image of a card.